version: '3'
services:
  server:
    container_name: nest-app
    image: nest-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=nestjs_db

  db:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nestjs_db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
